// GENERATED by scripts/optimize-bg.mjs — do not edit by hand.
// 16px placeholder for the stadium backdrop, inlined so there is no
// flash of empty background before the full image decodes.
export const BACKGROUND_BLUR_DATA_URL =
  "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABQBACdASoQABwAPu1iqU2ppaOiMAgBMB2JaACdMoADTtvNTVy6RKnSLSXUAP7vJvKyAhcpl3NtCRkyOXDLZFY/ZYGHku7k7MQG53PWaONS/BnglsjggDRjmlADdR5TgTuvImGNS3ppTnkVhhbNybUJp4q1HzZotQUjTcbbskqPdxwdpJMiIVhdiE2EAAAA";
