#!/usr/bin/env node
/**
 * Prepares the stadium backdrop for the web.
 *
 * The source drop is a ~2.2 MB PNG. Shipping that as a page background would
 * blow the Lighthouse performance budget in §13 on its own, so this produces:
 *
 *   public/back.webp      full-resolution WebP, the source next/image reads
 *   public/back-blur.txt  a tiny base64 WebP for the blur-up placeholder
 *
 * Re-run after replacing public/back.png:
 *   node scripts/optimize-bg.mjs
 */

import { readFile, writeFile, stat } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = resolve(ROOT, "public/back.png");
const OUT_WEBP = resolve(ROOT, "public/back.webp");
const OUT_BLUR = resolve(ROOT, "lib/background-blur.ts");

/**
 * How much of the top to discard, as a fraction of height.
 *
 * 0 = ship the whole frame, which is the current choice. The maths behind it:
 * the source is portrait (aspect 0.563), so under object-cover a phone
 * (390x800) shows 100% of the image's height and ~87% of its width — the
 * entire composition, sky to pitch. Cropping would throw away detail that a
 * phone can actually display.
 *
 * A desktop viewport can only ever show ~35% of the height, so it takes a band
 * from the middle instead (see object-center in components/app-background).
 * That is a limit of putting a portrait image behind a landscape viewport, not
 * something compression can solve.
 */
const CROP_TOP_FRACTION = 0;

const kb = (n) => `${(n / 1024).toFixed(0)} KB`;

const input = await readFile(SRC);
const meta = await sharp(input).metadata();
console.log(`source: ${meta.width}x${meta.height}  ${kb(input.length)}`);

const cropTop = Math.round(meta.height * CROP_TOP_FRACTION);
const cropped = () =>
  cropTop > 0
    ? sharp(input).extract({
        left: 0,
        top: cropTop,
        width: meta.width,
        height: meta.height - cropTop,
      })
    : sharp(input);
console.log(
  cropTop > 0
    ? `crop:   dropping top ${cropTop}px -> ${meta.width}x${meta.height - cropTop}`
    : `crop:   none — shipping the full ${meta.width}x${meta.height} frame`
);

// Quality 72 is the point where this particular image — large flat areas of
// dark sky with thin neon strokes — stops losing anything visible. The strokes
// are the only high-frequency detail and they survive well.
const webp = await cropped().webp({ quality: 72, effort: 6 }).toBuffer();
await writeFile(OUT_WEBP, webp);
console.log(
  `back.webp: ${kb(webp.length)}  (${(
    (1 - webp.length / input.length) * 100
  ).toFixed(0)}% smaller)`
);

// 16px-wide placeholder, inlined into the markup so there is no flash of empty
// background before the real image decodes.
const blur = await cropped()
  .resize(16)
  .webp({ quality: 40 })
  .toBuffer();
const dataUri = `data:image/webp;base64,${blur.toString("base64")}`;
await writeFile(
  OUT_BLUR,
  `// GENERATED by scripts/optimize-bg.mjs — do not edit by hand.
` +
    `// 16px placeholder for the stadium backdrop, inlined so there is no
` +
    `// flash of empty background before the full image decodes.
` +
    `export const BACKGROUND_BLUR_DATA_URL =
  "${dataUri}";
`
);
console.log(`lib/background-blur.ts: ${dataUri.length} char data URI`);

const after = await stat(OUT_WEBP);
if (after.size > 400 * 1024) {
  console.warn(
    `\nWARNING: ${kb(after.size)} is still heavy for a background. Consider ` +
      `downscaling the source or raising compression.`
  );
}
